steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
    '--build-arg', 'VITE_PAX_ENV=${_VITE_PAX_ENV}',
    '--build-arg', 'SOCKET_URL=${_SOCKET_URL}',
    '--build-arg', 'BACKEND_URL=${_BACKEND_URL}',
    '-t', '${_IMAGE_URL}:latest',
    '.']
images:
    - '${_IMAGE_URL}'
