services:

  db:
    restart: always
    image: 'postgres:14'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      POSTGRES_USER: app_rpm
      POSTGRES_PASSWORD: ez
      POSTGRES_DB: dbmodels
    volumes:
      - pax-db-data:/var/lib/postgresql/data

  liquibase:
    build: ./liquibase
    env_file:
      - ./.env.local
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
    depends_on:
      - "db"

  backend:
    restart: always
    build: ./backend
    env_file:
      - ./.env.local
    ports:
      - '3001:3001'
    expose:
      - '3001'
    environment:
      INSTANCE_UNIX_SOCKET: "db"
      PAX_FIREBASE_AUTH_DISABLED: "true"
    depends_on:
      db:
        condition: service_started
      liquibase:
        condition: service_completed_successfully

  frontend:
    build:
      context: .
      args:
        REACT_APP_PAX_APP_ENV:
        REACT_APP_PAX_SOCKET_URL:
        REACT_APP_PAX_BACKEND_URL:
        REACT_APP_AUTH_DOMAIN:
        REACT_APP_PAX_FIREBASE_API_KEY:
        REACT_APP_PAX_GOOGLE_PROJECT_ID:
    env_file:
      - ./.env.local
    environment:
      PORT: '3000'
    ports:
      - '3000:3000'
    expose:
      - '3000'

volumes:
  pax-db-data:
