services:
  db:
    image: 'postgres:14'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      POSTGRES_USER: app_rpm
      POSTGRES_PASSWORD: ez
      POSTGRES_DB: dbmodels
    volumes:
      - pax-db-data:/var/lib/postgresql/data

volumes:
  pax-db-data:
