name: pax-imperia-js build

on:
  push:
    paths:
      - '.github/workflows/pax-imperia-js.yml'
      - 'pax-imperia-js/**/*.js'
      - 'pax-imperia-js/**/*.jsx'
      - 'pax-imperia-js/**/*.cjs'
      - 'pax-imperia-js/**/*.json'
      - 'pax-imperia-js/**/*.conf'
      - 'pax-imperia-js/**/*.html'
      - 'pax-imperia-js/**/*.css'
      - 'pax-imperia-js/**/*.jpeg'
      - 'pax-imperia-js/**/*.png'
      - 'pax-imperia-js/**/*.svg'
      - 'pax-imperia-js/**/*.bin'
      - 'pax-imperia-js/**/*.gltf'
      - 'pax-imperia-js/**/*.fbx'

jobs:
  build:
    defaults:
      run:
        working-directory: ./pax-imperia-js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
