name: pax-imperia-js build

on:
  push:
    paths:
      - 'pax-imperia-js/**'

jobs:
  build:
    defaults:
      run:
        working-directory: ./pax-imperia-js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
